source 'https://rubygems.org'

gem 'fastup', path: '../..'

# top downloaded gems according to rubygems.org 2018-08-17 with some
# deletions
#
# for page in {1..50}; do curl -sf "https://rubygems.org/stats?page=$page" |  grep -E '\s+<h3.*/gems/' | sed -r 's,.*>([^><]+)</a></h3>,\1,'; done
pool = File.read('topgems').lines.map(&:strip).reject{ |x| x.empty? } - %w(
  bson_ext
  bundler
  chef
  cocoapods
  cocoapods-core
  inspec
  foreman
  mysql2
  money
  pg
  rb-inotify
  therubyracer
  train
  quiet_assets
  fog-profitbricks
  fog-rackspace
  fog-brightbox
  fog-softlayer
  fog-dynect
  fog-google
  countries
  aws-sdk-v1
  curb
  fog
  mysql
  rmagick
  sqlite3

  sinatra
  factory_girl
  factory_girl_rails
  polyglot
  treetop

  json_pure
  celluloid
  cocaine

  ohai
  chef-config
  chef-sugar

  bootstrap-sass
  bourbon
  sass-rails

  puppet

  safe_yaml
)

pool.first(ENV.fetch('GEMS_COUNT', pool.size).to_i).each do |name|
  gem(name)
end

